# Generated by Django 4.2.6 on 2023-11-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='new_choice_text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
