# Generated by Django 4.2.6 on 2023-11-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_new_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='new_question_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
